spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/online_retailers?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
    username: root
    password: root
  mvc:
    view: 
      prefix: /
      suffix: .jsp
server:
  port: 80
#  servlet:  
#   context-path: /lhs 
mybatis:
   mapper-locations: classpath:com/example/demo/or/mapper/*.xml

